---
title: "Introduction to seecolor"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r comment="", results="asis", echo=FALSE}
suppressMessages({
  library(seecolor)
  library(ggplot2)
  library(fansi)
  library(crayon)
})
old.hooks <- fansi::set_knit_hooks(knitr::knit_hooks)
options(crayon.enabled=TRUE)
```

## Use the cursor to select object to print in the console.

```{r, eval = FALSE}
# Highlight objects by cursor to show the contained colors
pick_color()

# Change output styles, "ribbon" or "mosaic"
pick_color(type = "r")

# Change the length of the color blocks
pick_color(blank.len = 1)
```



## Use `print_color` to print color literals, palettes and ggplot2 objects.

```{r}
print_color(c("red", "navy", "tomato", "#521354", "sienna"))
print_color(palette())
print_color(colors()[seq(1, 100, 5)], blank.len = 4)
print_color(palette(rainbow(6)))
p1 <- ggplot(mpg) +
  geom_point(aes(displ, cyl, color = manufacturer))
print_color(p1)
p2 <- ggplot(iris) +
  geom_point(aes(Sepal.Length, Petal.Length, color = Petal.Width))
print_color(p2)
```


## Use `open_sample()` to open a sample file to have a instant try.

```{r, eval=FALSE}
# Open the pre-defined test file
open_sample()
```

